// function to create a random number generator using the math.random built in function
 function randomnumbergenerator(min, max) {
    return Math.random() * (max - min) + min;
}



// function that filters the numbers generated by the randomnumbergenerator to only output numbers from 1-10 inclusive.
function numberfilter (min, max) {
    
    // min and max limiters
    max = Math.floor(max);
    
    //return statement for filtered numbers in function
    return Math.floor(Math.random() * (max - min + 1)) + min;
}


